# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc_template/generate_lesson_plan.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'grpc_template/generate_lesson_plan.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(grpc_template/generate_lesson_plan.proto\x12\x0blesson_plan\"\x96\x01\n\x11LessonPlanRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x10\n\x08\x66ile_url\x18\x02 \x01(\t\x12\x14\n\x0cteacher_note\x18\x04 \x01(\t\x12\x0e\n\x06\x66ormat\x18\x05 \x01(\t\x12\x12\n\nteacher_id\x18\x06 \x01(\x04\x12\x11\n\tcourse_id\x18\x07 \x01(\x04\"%\n\x12LessonPlanResponse\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t2e\n\x08L2_tools\x12Y\n\x12GenerateLessonPlan\x12\x1e.lesson_plan.LessonPlanRequest\x1a\x1f.lesson_plan.LessonPlanResponse\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_template.generate_lesson_plan_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LESSONPLANREQUEST']._serialized_start=58
  _globals['_LESSONPLANREQUEST']._serialized_end=208
  _globals['_LESSONPLANRESPONSE']._serialized_start=210
  _globals['_LESSONPLANRESPONSE']._serialized_end=247
  _globals['_L2_TOOLS']._serialized_start=249
  _globals['_L2_TOOLS']._serialized_end=350
# @@protoc_insertion_point(module_scope)
