// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/generate_lesson_plan.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LessonPlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	FileUrl       string                 `protobuf:"bytes,2,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`
	TeacherNote   string                 `protobuf:"bytes,4,opt,name=teacher_note,json=teacherNote,proto3" json:"teacher_note,omitempty"`
	Format        string                 `protobuf:"bytes,5,opt,name=format,proto3" json:"format,omitempty"`
	TeacherId     uint64                 `protobuf:"varint,6,opt,name=teacher_id,json=teacherId,proto3" json:"teacher_id,omitempty"`
	CourseId      *uint64                `protobuf:"varint,7,opt,name=course_id,json=courseId,proto3,oneof" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LessonPlanRequest) Reset() {
	*x = LessonPlanRequest{}
	mi := &file_proto_generate_lesson_plan_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LessonPlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LessonPlanRequest) ProtoMessage() {}

func (x *LessonPlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_generate_lesson_plan_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LessonPlanRequest.ProtoReflect.Descriptor instead.
func (*LessonPlanRequest) Descriptor() ([]byte, []int) {
	return file_proto_generate_lesson_plan_proto_rawDescGZIP(), []int{0}
}

func (x *LessonPlanRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *LessonPlanRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *LessonPlanRequest) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *LessonPlanRequest) GetTeacherNote() string {
	if x != nil {
		return x.TeacherNote
	}
	return ""
}

func (x *LessonPlanRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *LessonPlanRequest) GetTeacherId() uint64 {
	if x != nil {
		return x.TeacherId
	}
	return 0
}

func (x *LessonPlanRequest) GetCourseId() uint64 {
	if x != nil && x.CourseId != nil {
		return *x.CourseId
	}
	return 0
}

type LessonPlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LessonPlanResponse) Reset() {
	*x = LessonPlanResponse{}
	mi := &file_proto_generate_lesson_plan_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LessonPlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LessonPlanResponse) ProtoMessage() {}

func (x *LessonPlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_generate_lesson_plan_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LessonPlanResponse.ProtoReflect.Descriptor instead.
func (*LessonPlanResponse) Descriptor() ([]byte, []int) {
	return file_proto_generate_lesson_plan_proto_rawDescGZIP(), []int{1}
}

func (x *LessonPlanResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_proto_generate_lesson_plan_proto protoreflect.FileDescriptor

const file_proto_generate_lesson_plan_proto_rawDesc = "" +
	"\n" +
	" proto/generate_lesson_plan.proto\x12\vlesson_plan\"\xf0\x01\n" +
	"\x11LessonPlanRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x19\n" +
	"\bfile_url\x18\x02 \x01(\tR\afileUrl\x12!\n" +
	"\fteacher_note\x18\x04 \x01(\tR\vteacherNote\x12\x16\n" +
	"\x06format\x18\x05 \x01(\tR\x06format\x12\x1d\n" +
	"\n" +
	"teacher_id\x18\x06 \x01(\x04R\tteacherId\x12 \n" +
	"\tcourse_id\x18\a \x01(\x04H\x00R\bcourseId\x88\x01\x01B\f\n" +
	"\n" +
	"_course_id\".\n" +
	"\x12LessonPlanResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent2e\n" +
	"\bL2_tools\x12Y\n" +
	"\x12GenerateLessonPlan\x12\x1e.lesson_plan.LessonPlanRequest\x1a\x1f.lesson_plan.LessonPlanResponse\"\x000\x01B\x17Z\x15smart-elearning/protob\x06proto3"

var (
	file_proto_generate_lesson_plan_proto_rawDescOnce sync.Once
	file_proto_generate_lesson_plan_proto_rawDescData []byte
)

func file_proto_generate_lesson_plan_proto_rawDescGZIP() []byte {
	file_proto_generate_lesson_plan_proto_rawDescOnce.Do(func() {
		file_proto_generate_lesson_plan_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_generate_lesson_plan_proto_rawDesc), len(file_proto_generate_lesson_plan_proto_rawDesc)))
	})
	return file_proto_generate_lesson_plan_proto_rawDescData
}

var file_proto_generate_lesson_plan_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_generate_lesson_plan_proto_goTypes = []any{
	(*LessonPlanRequest)(nil),  // 0: lesson_plan.LessonPlanRequest
	(*LessonPlanResponse)(nil), // 1: lesson_plan.LessonPlanResponse
}
var file_proto_generate_lesson_plan_proto_depIdxs = []int32{
	0, // 0: lesson_plan.L2_tools.GenerateLessonPlan:input_type -> lesson_plan.LessonPlanRequest
	1, // 1: lesson_plan.L2_tools.GenerateLessonPlan:output_type -> lesson_plan.LessonPlanResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_generate_lesson_plan_proto_init() }
func file_proto_generate_lesson_plan_proto_init() {
	if File_proto_generate_lesson_plan_proto != nil {
		return
	}
	file_proto_generate_lesson_plan_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_generate_lesson_plan_proto_rawDesc), len(file_proto_generate_lesson_plan_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_generate_lesson_plan_proto_goTypes,
		DependencyIndexes: file_proto_generate_lesson_plan_proto_depIdxs,
		MessageInfos:      file_proto_generate_lesson_plan_proto_msgTypes,
	}.Build()
	File_proto_generate_lesson_plan_proto = out.File
	file_proto_generate_lesson_plan_proto_goTypes = nil
	file_proto_generate_lesson_plan_proto_depIdxs = nil
}
