server:
  mode: "debug" # release
  port: "8080"
database:
  postgresql:
    db_url: ""
    db_user: ""
    db_password: ""
jwt:
  secret_key: ""
  expire_time: "2" # 2 hour
resources:
  default_avatar:
    student: "https://tse2.mm.bing.net/th/id/OIP.Nv0nGIfNJvPR3rNyKoXOEgHaHa?r=0&rs=1&pid=ImgDetMain&o=7&rm=3"
    teacher: "https://static.vecteezy.com/system/resources/previews/007/023/565/non_2x/avatar-of-a-young-smiling-guy-in-a-green-t-shirt-portrait-of-a-student-partner-sales-manager-for-advice-bots-support-illustration-flat-vector.jpg"