/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardDashboardRouteImport } from './routes/dashboard/_dashboard'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as DashboardDashboardIndexRouteImport } from './routes/dashboard/_dashboard.index'
import { Route as DashboardDashboardToolsRouteImport } from './routes/dashboard/_dashboard.tools'
import { Route as DashboardDashboardDocumentsRouteImport } from './routes/dashboard/_dashboard.documents'
import { Route as DashboardDashboardChatRouteImport } from './routes/dashboard/_dashboard.chat'
import { Route as DashboardDashboardAccountRouteImport } from './routes/dashboard/_dashboard.account'
import { Route as DashboardDashboardCourseDashboardCourseRouteImport } from './routes/dashboard/_dashboard.course/_dashboard.course'
import { Route as DashboardDashboardCourseDashboardCourseIndexRouteImport } from './routes/dashboard/_dashboard.course/_dashboard.course.index'
import { Route as DashboardDashboardCourseDashboardCourseStudentsRouteImport } from './routes/dashboard/_dashboard.course/_dashboard.course.students'
import { Route as DashboardDashboardCourseDashboardCourseListRouteImport } from './routes/dashboard/_dashboard.course/_dashboard.course.list'

const DashboardRouteImport = createFileRoute('/dashboard')()

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDashboardRoute = DashboardDashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDashboardIndexRoute = DashboardDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardDashboardRoute,
} as any)
const DashboardDashboardToolsRoute = DashboardDashboardToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => DashboardDashboardRoute,
} as any)
const DashboardDashboardDocumentsRoute =
  DashboardDashboardDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => DashboardDashboardRoute,
  } as any)
const DashboardDashboardChatRoute = DashboardDashboardChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => DashboardDashboardRoute,
} as any)
const DashboardDashboardAccountRoute =
  DashboardDashboardAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => DashboardDashboardRoute,
  } as any)
const DashboardDashboardCourseDashboardCourseRoute =
  DashboardDashboardCourseDashboardCourseRouteImport.update({
    id: '/course/_dashboard/course',
    path: '/course/course',
    getParentRoute: () => DashboardDashboardRoute,
  } as any)
const DashboardDashboardCourseDashboardCourseIndexRoute =
  DashboardDashboardCourseDashboardCourseIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardDashboardCourseDashboardCourseRoute,
  } as any)
const DashboardDashboardCourseDashboardCourseStudentsRoute =
  DashboardDashboardCourseDashboardCourseStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => DashboardDashboardCourseDashboardCourseRoute,
  } as any)
const DashboardDashboardCourseDashboardCourseListRoute =
  DashboardDashboardCourseDashboardCourseListRouteImport.update({
    id: '/list',
    path: '/list',
    getParentRoute: () => DashboardDashboardCourseDashboardCourseRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard': typeof DashboardDashboardRouteWithChildren
  '/dashboard/account': typeof DashboardDashboardAccountRoute
  '/dashboard/chat': typeof DashboardDashboardChatRoute
  '/dashboard/documents': typeof DashboardDashboardDocumentsRoute
  '/dashboard/tools': typeof DashboardDashboardToolsRoute
  '/dashboard/': typeof DashboardDashboardIndexRoute
  '/dashboard/course/course': typeof DashboardDashboardCourseDashboardCourseRouteWithChildren
  '/dashboard/course/course/list': typeof DashboardDashboardCourseDashboardCourseListRoute
  '/dashboard/course/course/students': typeof DashboardDashboardCourseDashboardCourseStudentsRoute
  '/dashboard/course/course/': typeof DashboardDashboardCourseDashboardCourseIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard': typeof DashboardDashboardIndexRoute
  '/dashboard/account': typeof DashboardDashboardAccountRoute
  '/dashboard/chat': typeof DashboardDashboardChatRoute
  '/dashboard/documents': typeof DashboardDashboardDocumentsRoute
  '/dashboard/tools': typeof DashboardDashboardToolsRoute
  '/dashboard/course/course/list': typeof DashboardDashboardCourseDashboardCourseListRoute
  '/dashboard/course/course/students': typeof DashboardDashboardCourseDashboardCourseStudentsRoute
  '/dashboard/course/course': typeof DashboardDashboardCourseDashboardCourseIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/_dashboard': typeof DashboardDashboardRouteWithChildren
  '/dashboard/_dashboard/account': typeof DashboardDashboardAccountRoute
  '/dashboard/_dashboard/chat': typeof DashboardDashboardChatRoute
  '/dashboard/_dashboard/documents': typeof DashboardDashboardDocumentsRoute
  '/dashboard/_dashboard/tools': typeof DashboardDashboardToolsRoute
  '/dashboard/_dashboard/': typeof DashboardDashboardIndexRoute
  '/dashboard/_dashboard/course/_dashboard/course': typeof DashboardDashboardCourseDashboardCourseRouteWithChildren
  '/dashboard/_dashboard/course/_dashboard/course/list': typeof DashboardDashboardCourseDashboardCourseListRoute
  '/dashboard/_dashboard/course/_dashboard/course/students': typeof DashboardDashboardCourseDashboardCourseStudentsRoute
  '/dashboard/_dashboard/course/_dashboard/course/': typeof DashboardDashboardCourseDashboardCourseIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard'
    | '/dashboard/account'
    | '/dashboard/chat'
    | '/dashboard/documents'
    | '/dashboard/tools'
    | '/dashboard/'
    | '/dashboard/course/course'
    | '/dashboard/course/course/list'
    | '/dashboard/course/course/students'
    | '/dashboard/course/course/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard'
    | '/dashboard/account'
    | '/dashboard/chat'
    | '/dashboard/documents'
    | '/dashboard/tools'
    | '/dashboard/course/course/list'
    | '/dashboard/course/course/students'
    | '/dashboard/course/course'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard'
    | '/dashboard/_dashboard'
    | '/dashboard/_dashboard/account'
    | '/dashboard/_dashboard/chat'
    | '/dashboard/_dashboard/documents'
    | '/dashboard/_dashboard/tools'
    | '/dashboard/_dashboard/'
    | '/dashboard/_dashboard/course/_dashboard/course'
    | '/dashboard/_dashboard/course/_dashboard/course/list'
    | '/dashboard/_dashboard/course/_dashboard/course/students'
    | '/dashboard/_dashboard/course/_dashboard/course/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/_dashboard': {
      id: '/dashboard/_dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/_dashboard/': {
      id: '/dashboard/_dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardDashboardIndexRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
    '/dashboard/_dashboard/tools': {
      id: '/dashboard/_dashboard/tools'
      path: '/tools'
      fullPath: '/dashboard/tools'
      preLoaderRoute: typeof DashboardDashboardToolsRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
    '/dashboard/_dashboard/documents': {
      id: '/dashboard/_dashboard/documents'
      path: '/documents'
      fullPath: '/dashboard/documents'
      preLoaderRoute: typeof DashboardDashboardDocumentsRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
    '/dashboard/_dashboard/chat': {
      id: '/dashboard/_dashboard/chat'
      path: '/chat'
      fullPath: '/dashboard/chat'
      preLoaderRoute: typeof DashboardDashboardChatRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
    '/dashboard/_dashboard/account': {
      id: '/dashboard/_dashboard/account'
      path: '/account'
      fullPath: '/dashboard/account'
      preLoaderRoute: typeof DashboardDashboardAccountRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
    '/dashboard/_dashboard/course/_dashboard/course': {
      id: '/dashboard/_dashboard/course/_dashboard/course'
      path: '/course/course'
      fullPath: '/dashboard/course/course'
      preLoaderRoute: typeof DashboardDashboardCourseDashboardCourseRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
    '/dashboard/_dashboard/course/_dashboard/course/': {
      id: '/dashboard/_dashboard/course/_dashboard/course/'
      path: '/'
      fullPath: '/dashboard/course/course/'
      preLoaderRoute: typeof DashboardDashboardCourseDashboardCourseIndexRouteImport
      parentRoute: typeof DashboardDashboardCourseDashboardCourseRoute
    }
    '/dashboard/_dashboard/course/_dashboard/course/students': {
      id: '/dashboard/_dashboard/course/_dashboard/course/students'
      path: '/students'
      fullPath: '/dashboard/course/course/students'
      preLoaderRoute: typeof DashboardDashboardCourseDashboardCourseStudentsRouteImport
      parentRoute: typeof DashboardDashboardCourseDashboardCourseRoute
    }
    '/dashboard/_dashboard/course/_dashboard/course/list': {
      id: '/dashboard/_dashboard/course/_dashboard/course/list'
      path: '/list'
      fullPath: '/dashboard/course/course/list'
      preLoaderRoute: typeof DashboardDashboardCourseDashboardCourseListRouteImport
      parentRoute: typeof DashboardDashboardCourseDashboardCourseRoute
    }
  }
}

interface DashboardDashboardCourseDashboardCourseRouteChildren {
  DashboardDashboardCourseDashboardCourseListRoute: typeof DashboardDashboardCourseDashboardCourseListRoute
  DashboardDashboardCourseDashboardCourseStudentsRoute: typeof DashboardDashboardCourseDashboardCourseStudentsRoute
  DashboardDashboardCourseDashboardCourseIndexRoute: typeof DashboardDashboardCourseDashboardCourseIndexRoute
}

const DashboardDashboardCourseDashboardCourseRouteChildren: DashboardDashboardCourseDashboardCourseRouteChildren =
  {
    DashboardDashboardCourseDashboardCourseListRoute:
      DashboardDashboardCourseDashboardCourseListRoute,
    DashboardDashboardCourseDashboardCourseStudentsRoute:
      DashboardDashboardCourseDashboardCourseStudentsRoute,
    DashboardDashboardCourseDashboardCourseIndexRoute:
      DashboardDashboardCourseDashboardCourseIndexRoute,
  }

const DashboardDashboardCourseDashboardCourseRouteWithChildren =
  DashboardDashboardCourseDashboardCourseRoute._addFileChildren(
    DashboardDashboardCourseDashboardCourseRouteChildren,
  )

interface DashboardDashboardRouteChildren {
  DashboardDashboardAccountRoute: typeof DashboardDashboardAccountRoute
  DashboardDashboardChatRoute: typeof DashboardDashboardChatRoute
  DashboardDashboardDocumentsRoute: typeof DashboardDashboardDocumentsRoute
  DashboardDashboardToolsRoute: typeof DashboardDashboardToolsRoute
  DashboardDashboardIndexRoute: typeof DashboardDashboardIndexRoute
  DashboardDashboardCourseDashboardCourseRoute: typeof DashboardDashboardCourseDashboardCourseRouteWithChildren
}

const DashboardDashboardRouteChildren: DashboardDashboardRouteChildren = {
  DashboardDashboardAccountRoute: DashboardDashboardAccountRoute,
  DashboardDashboardChatRoute: DashboardDashboardChatRoute,
  DashboardDashboardDocumentsRoute: DashboardDashboardDocumentsRoute,
  DashboardDashboardToolsRoute: DashboardDashboardToolsRoute,
  DashboardDashboardIndexRoute: DashboardDashboardIndexRoute,
  DashboardDashboardCourseDashboardCourseRoute:
    DashboardDashboardCourseDashboardCourseRouteWithChildren,
}

const DashboardDashboardRouteWithChildren =
  DashboardDashboardRoute._addFileChildren(DashboardDashboardRouteChildren)

interface DashboardRouteChildren {
  DashboardDashboardRoute: typeof DashboardDashboardRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDashboardRoute: DashboardDashboardRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
