@baseUrl = http://34.66.124.67/api/v1
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsInVzZXJfaWQiOjMsInVzZXJuYW1lIjoiTWluaCBIaeG6v3UiLCJlbWFpbCI6ImhpZmV1MGRAZ21haWwuY29tIiwic2NvcGUiOiJTVFVERU5UIiwiZXhwIjoxNzUxNDAyMjE0LCJpYXQiOjE3NTEzOTUwMTR9.pSFrN49cNq9RdT_7uOXEovTNn9WKdBc8m2ghXPwDglU

POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "email" : "hifeu0d@gmail.com",
    "username": "Minh Hiếu",
    "password" : "123456",
    "type": "STUDENT" 
}

###
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "hifeu0d@gmail.com",
    "password": "123456"
}


###
POST {{baseUrl}}/teacher/courses
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Python cơ bản",
    "description": "123213",
    "visibility": "PUBLIC"
}

###
GET {{baseUrl}}/teacher/courses?page=0&limit=2
Authorization: Bearer {{token}} 